### PR TITLE
Update lambda function to take a zip file and use Go by default.

### PR DESCRIPTION
**Pull request by itsdalmo**

### CODE REVIEW

**Comment by itsdalmo** [comment]
No, don't think it's a big issue. People should be locked to a specific version anyhow :)

**Comment by itsdalmo** [comment]
Let me fix the error before merging

**Comment by mikael-lindstrom** [comment]
Tag new release once merged?

**Comment by itsdalmo** [comment]
Let's worry about the broken CloudTrail module later 👍 Agreed, tag new release

**Pull request merged**
